config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :users
  resources :byenotes

  get 'hospice' => 'welcome#hospice'
  get 'organ-donation' => 'welcome#organ'
  get 'funeral' => 'welcome#funeral'

  get 'profile' => 'users#show'
  get 'theword' => 'users#theword'

  get 'read' => 'welcome#read'
  get 'search' => 'welcome#search'
  post 'search' => 'welcome#search_post'

  namespace :admin do
    resources :byenotes
    get 'index' => 'byenotes#index'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  devise :omniauthable, :omniauth_providers => [:facebook]
  before_create :set_page_url

  has_one :byenote, :dependent => :delete
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.fullname = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      user.confirmed_at = Time.now
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if session[:byenote_params]
        user.byenote = Byenote.new(session[:byenote_params])
      end
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def set_page_url
    self.page_url = SecureRandom.urlsafe_base64()
  end

  def admin?
    self.role == "admin"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def theword #再見手札頁面
    @user = current_user
    if @user.byenote
      @byenote = @user.byenote
    else
      @byenote = Byenote.new
      @byenote.user_id = current_user.id
    end
  end

  def show #個人資料修改頁面
    @user = current_user
    @byenote = @user.byenote
  end

  private

end

app/helpers/users_helper.rb
module UsersHelper
  def new_or_edit_byenote
    if @user.byenote
      "修改再見手札"
    else
      "你還沒有填寫再見手札呢~快點完成它吧!"
    end
  end

end

app/views/users/_user_header.html.erb
    <!--=== Header ===-->
    <div class="header header-sticky">
        <div class="container">
            <!-- Logo -->
            <a class="navbar-brand" style="padding:40px;font-size:30px;color:#72c02c;" href="index.html">theWord - 再見手札</a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul class="loginbar pull-right">
                    <li><a href="page_faq.html">關於我們</a></li>
                    <li class="topbar-devider"></li>
                    <li>
                        <% if user_signed_in? %>
                          Logged in as <strong><%= current_user.email %></strong>.
                          <%= link_to "登出", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        <% else %>
                          <%= link_to "註冊", new_user_registration_path, :class => 'navbar-link'  %> |
                          <%= link_to "登入", new_user_session_path, :class => 'navbar-link'  %> |
                          <%= link_to "Facebook登入", user_omniauth_authorize_path(:facebook) %>
                        <% end %>
                    </li>
                </ul>
            </div>
            <!-- End Topbar -->

            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">theWord</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse mega-menu navbar-responsive-collapse">
            <div class="container">
                <ul class="nav navbar-nav">
                    <!-- Home -->
                    <li class="page-scroll"><%= link_to '服務說明', root_path %></li>
                    <li class="page-scroll"><%= link_to '再見手札', path %></li>
                    <li class="page-scroll"><%= link_to '個人資料', profile_path %></li>
                    <li class="page-scroll"><%= link_to '服務說明', root_path %></li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->

app/views/users/theword.html.erb
<div class="wrapper">
  <div id="theword" class="row fill-all-form">
    <div class="col-md-8 col-md-offset-2 col-xs-12 byenote-title">
      <h2 class=""><%= new_or_edit_byenote %></h2>
      <h3>我的再見手札頁面: <%= link_to "theword.tw/read?theword=#{@user.page_url}", read_path(:theword => @user.page_url) %> </h3>
    </div>
    <div class="col-md-8 col-md-offset-2 col-xs-12 form-page tag-box-v2 byenote-form-page">
      <%= form_for(@byenote) do |f| %>
        <%= render :partial => "welcome/organ_form", :locals => {:f => f } %>
        <%= render :partial => "welcome/hospice_form", :locals => {:f => f } %>
        <%= render :partial => "welcome/funeral_form", :locals => {:f => f } %>
        <div class="row">
          <div class="heading"><h3 style="text-align:center;"><legend>給親友的話</legend></h3></div>
          <%= f.text_area :some_message, rows: 4, :class => "message_textarea", :placeholder => "與親朋好友們道謝、道歉、道愛、道別" %>
        </div>
        <div class="margin-bottom-20"></div>
        <div class="row">
              <button type="submit" class="btn btn-u" style="width:100%;padding:10px;">更新</button>
        </div>
      <% end %>
    </div>
    <script>
    if(document.getElementById('byenote_donate_select_partial').checked){
      $("#organ_checkbox_form").show();
    }
    else{
      $("#organ_checkbox_form").hide();
    }
    </script>
  </div>
</div>