config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :users
  resources :byenotes

  get 'hospice' => 'welcome#hospice'
  get 'organ-donation' => 'welcome#organ'
  get 'funeral' => 'welcome#funeral'

  get 'profile' => 'users#show'
  get 'theword' => 'users#theword'

  get 'read' => 'welcome#read'
  get 'search' => 'welcome#search'
  post 'search' => 'welcome#search_post'

  namespace :admin do
    resources :byenotes
    get 'index' => 'byenotes#index'
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :new_or_current_user

  def index
    @byenote = Byenote.new
    @btitle = "1分鐘寫完你的生前意願"
    @stitle = "親友能隨時查詢你的器捐意願、安寧意願、喪葬意願"
  end

  def organ
    @byenote = Byenote.new
    @btitle = "最後一天別讓家人煩腦"
    @stitle = "留下你的器捐意願"
  end

  def hospice
    @byenote = Byenote.new
    @btitle = "如果我沒醒過來<br/>不要串通醫師凌遲我!"
    @stitle = "留下你的安寧意願"
  end

  def funeral
    @byenote = Byenote.new
    @btitle = "最後一天別讓家人煩腦"
    @stitle = "留下你的喪葬意願"
  end

  def search

  end

  def search_post
    @user = User.find_by_email params[:search_email]
    @user? @byenote = @user.byenote : @byenote = nil

    if @byenote
      redirect_to read_path(:theword => @user.page_url)
      flash[:success] = "你查詢的是 #{@user.email} 的再見手札"
    else
      flash[:fault] = "#{params[:search_email]} 尚未填寫再見手札"
      render :search
    end
  end

  def read
    @user = User.find_by_page_url(params[:theword])
    @byenote = @user.byenote
    if @byenote
      render :read
    else
      redirect_to :search
    end
  end

  private

  def new_or_current_user
    if current_user
      @user = current_user
      @byenote = @user.byenote
    else
      @user = User.new
      @byenote = Byenote.new
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
  require 'json'
  def youtube (aaaaa)
    %Q(<iframe width="100%" height="310" src="//www.youtube.com/embed/#{aaaaa}" frameborder="0" allowfullscreen></iframe>)
  end
  def load_json_file( filepath )
    JSON.parse( File.read(filepath) )
  end
  def faq(filepath)
    organfaq = load_json_file(filepath)
    ofaq = ""
    keycount = 0
    organfaq.each{|key,value|
      ofaq << %Q(<h3 class="margin-top-30">#{key}</h3>)
      value.each{|key2,value2|
        keycount += 1
        ofaq << %Q(
              <div class="panel-group acc-v1" id="accordion">
                  <div class="panel panel-default">
                      <div class="panel-heading">
                          <h4 class="panel-title">
                              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse#{keycount}">
                                  <strong>Q. #{key2}</strong>
                              </a>
                          </h4>
                      </div>
                      <div id="collapse#{keycount}" class="panel-collapse collapse answer">
                          <div class="panel-body">
                              #{value2}
                          </div>
                      </div>
                  </div>
              </div>
          )

      }
    }
    ofaq
  end


end

app/views/welcome/_contactus.html.erb
<!-- Contacts BEGIN -->
<section id="contact" class="contacts-section2 bg-color-light">
    <div class="container content">
        <div class="title-v1 margin-bottom-10">
            <h2>聯絡我們</h2>
            <p>對我們的服務有想法、建議、疑問或抱怨嗎? 你可以在FB告訴我們!</p>
            <div class="fb-page" data-href="https://www.facebook.com/%E7%95%99%E4%B8%8B%E9%81%BA%E8%A8%80%E7%95%99%E4%B8%8B%E6%84%9B-1564354127160181/timeline/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"></div>
        </div>

<!--         <div class="col-md-8 col-md-push-2 col-sm-6 col-sm-push-2">
            <form action="" method="post">
                <div class="col-md-6 margin-bottom-20">
                    <input type="text" name="name" id="name" class="form-control" placeholder="Name">
                </div>
                <div class="col-md-6">
                    <input type="text" name="email" id="email" class="form-control" placeholder="Email *">
                </div>
                <div class="col-md-12">
                    <textarea rows="8" name="message" id="message" class="form-control" placeholder="Message"></textarea>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn-u">送出</button>
                </div>
            </form>
        </div> -->
    </div>
</section>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=882105101852973";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Contacts END -->

app/views/welcome/_faq.html.erb
<div class="panel-group acc-v1" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    <%= title %>
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
                <%= content %>
            </div>
        </div>
    </div>
</div>

app/views/welcome/_funeral_form.html.erb
<div class="row">
  <div class="heading"><h3 style="text-align:center;"><legend>喪葬意願</legend></h3></div>
  <%= f.text_area :funeral, :rows => 4, :class => "message_textarea", :placeholder => "你希望自己的告別式是什麼樣的氣氛? 放什麼音樂? 要長眠在哪裡? 試著寫下來吧!! (注意: 此項目開放不特定人查詢及閱覽，請避免個人隱私資訊)" %>
</div>

app/views/welcome/_header.html.erb
<div class="header header-sticky">
    <div class="container">
        <!-- Logo -->
        <%= link_to "再見手札", root_path, :class => "navbar-brand", :style => 'padding:40px 0px;font-size:30px;color:#72c02c;' %>
        <!-- End Logo -->

        <!-- Topbar -->
        <div class="topbar">
            <ul class="loginbar pull-right">
                <li>
                    <% if user_signed_in? %>
                      <strong><%= current_user.fullname || current_user.email %></strong>
                      <%= link_to "登出", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                      <%= link_to "註冊", new_user_registration_path, :class => 'navbar-link'  %> |
                      <%= link_to "登入", new_user_session_path, :class => 'navbar-link'  %>
                      <%#= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %>
                    <% end %>
                </li>
            </ul>
        </div>
        <!-- End Topbar -->

        <!-- Toggle get grouped for better mobile display -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">theWord</span>
            <span class="fa fa-bars"></span>
        </button>
        <!-- End Toggle -->
    </div><!--/end container-->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse mega-menu navbar-responsive-collapse">
        <div class="container">
            <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <li class="page-scroll"><%= link_to "Admin", admin_index_path %></li>
                    <% end %>
                    <li class="page-scroll"><%= link_to '再見手札', theword_path %></li>
                    <!-- <li class="page-scroll"><%#= link_to '個人資料', profile_path %></li> -->
                    <li class="page-scroll"><%= link_to '查詢親友意願', search_path %></li>
                    <li class="page-scroll"><a href="/#contact">聯絡我們</a></li>
                <% else %>
                    <li class="page-scroll"><%= link_to '首頁', root_path %></li>
                    <li class="page-scroll"><%= link_to '器捐意願', organ_donation_path %></li>
                    <li class="page-scroll"><%= link_to '安寧意願', hospice_path %></li>
                    <li class="page-scroll"><%= link_to '查詢親友意願', search_path %></li>
                    <li class="page-scroll"><a href="/#contact">聯絡我們</a></li>
                <% end %>
            </ul>
        </div><!--/end container-->
    </div><!--/navbar-collapse-->
</div>

app/views/welcome/_hospice_form.html.erb
<div class="row">
  <div class="heading">
      <h3 style="text-align:center;"><legend>安寧意願</legend></h3>
  </div>
    <p>全名: 安寧緩和醫療暨維生醫療抉擇意願</p>
    <p>本人若罹患嚴重傷病,經醫師診斷認為不可治癒,且有醫學上之證據,近期內病程進行至死亡已屬不可避免時(末期病人),作以下之抉擇:</p>
    <!-- <p style="text-align:center;">(安寧緩和醫療暨維生醫療抉擇意願)</p> -->
    <div class="col-sm-6 col-sm-offset-4 col-xs-12  col-xs-offset-2">
      <label title="指為減輕或免除末期病人之生理、心理及靈性痛苦,施予緩解性、支持性之醫療照護,以增進其生活品質。" class="checkbox">
        <%= f.check_box :hospice_palliative, {}, 1, 0 %>接受 安寧緩和醫療<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseHospice1">(說明)</a></label>
  <div id="collapseHospice1" class="panel-collapse collapse">
      <div class="panel-body">
        指為減輕或免除末期病人之生理、心理及靈性痛苦,施予緩解性、支持性之醫療照護,以增進其生活品質。
      </div>
  </div>

      <label class="checkbox">
        <%= f.check_box :hospice_no_cpr, {}, 1, 0 %>接受 不施行心肺復甦術<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseHospice2">(說明)</a></label>
  <div id="collapseHospice2" class="panel-collapse collapse">
      <div class="panel-body">
        指對臨終、瀕死或無生命徵象之病人,不施予氣管內插管、體外心臟按壓、急救藥物注射、心臟電擊、心臟人工調頻、人工呼吸等標準急救程序或其他緊急救治行為。
      </div>
  </div>

      <label class="checkbox">
        <%= f.check_box :hospice_life_sustaining, {}, 1, 0 %>接受 不施行維生醫療<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseHospice3">(說明)</a></label>
  <div id="collapseHospice3" class="panel-collapse collapse">
      <div class="panel-body">
        指末期病人不施行用以維持生命徵象及延長其瀕死過程的醫療措施。
      </div>
  </div>


    </div>
</div>

app/views/welcome/_organ_form.html.erb
<div class="row">
  <div class="heading">

      <h3 style="text-align:center;"><legend>器捐意願</legend></h3>

  </div>
  <p>本人願意於生命之盡頭，捐贈可用器官，讓其他需要的病人能因此而獲得重生機會<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOrgan">(說明)</a></p>


  <div id="collapseOrgan" class="panel-collapse collapse">
      <div class="panel-body">
        <p>並不是每個人都有機會可以捐贈器官，一般『器官捐贈』係遭意外造成<u title="臨床所謂的「腦死」即是生命結束，視同死亡。由於近幾十年醫療科技的進步，腦死病人可以藉由呼吸器及藥物來暫時維持人體的呼吸和心跳、血壓等生理功能，但仍然難以超過兩星期。一旦除去呼吸器，腦死病人無法自行呼吸，心跳亦隨之停止。">腦死狀態</u>，醫院會徵求近親家屬兩位之書面同意書，且須經兩次腦死判定，方能完成捐贈心願。<br>完成後請分享再見手札給家人，使其了解您對器官捐贈的看法與決定。</p>
      </div>
  </div>

  <div style="padding:0px 20px;">
    <div class="col-sm-4 col-xs-12">
        <label class="radio content-boxes-v1 radio-v1"><%= f.radio_button :donate_select, "all", :onclick => "organSelectAll();" %><i class="rounded-x"></i>捐贈全部器官
        </label>
    </div>
    <div class="col-sm-4 col-xs-12">
        <label class="radio content-boxes-v1 radio-v1"><%= f.radio_button :donate_select, "partial", :onclick => "organSelectPartial();" %><i class="rounded-x"></i>捐贈部份器官</label>
    </div>
    <div class="col-sm-4 col-xs-12">
        <label class="radio content-boxes-v1 radio-v1"><%= f.radio_button :donate_select, "no", :onclick => "organSelectAll();" %><i class="rounded-x"></i>不要捐贈器官</label>
    </div>
    <div id="organ_checkbox_form" style="display:none;">
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_heart, {}, 1, 0 %>心臟</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_lung, {}, 1, 0 %>肺臟</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_liver, {}, 1, 0 %>肝臟</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_pancreas, {}, 1, 0 %>胰臟</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_kidney, {}, 1, 0 %>腎臟</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_smll_intestine, {}, 1, 0 %>小腸</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_cornea, {}, 1, 0 %>眼角膜</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_skin, {}, 1, 0 %>皮膚</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_skeleton, {}, 1, 0 %>骨骼</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_heart_valve, {}, 1, 0 %>心瓣膜</label></div>
      <div class="col-md-3 col-xs-4"><label class="checkbox"><%= f.check_box :donate_artery, {}, 1, 0 %>血管</label></div>
    </div>
  </div>
  <div class="margin-bottom-20"></div>
</div>

app/views/welcome/_slider.html.erb
  <!-- Interactive Slider v2 -->
  <div id="" class="interactive-slider-v2 index-slider">
      <div class="row">
          <h1><%= btitle.html_safe %></h1>
          <div class="col-sm-8 sub-active col-sm-push-2">
              <div class="subtitle"><h2 class="subtitle"><%= stitle.html_safe %></h2></div>
              <a href=<%= user_omniauth_authorize_path(:facebook) %> class="btn-u"><h3>使用Facebook登入 - 填寫再見手札</h3></a>
          </div>
      </div>
  </div>

app/views/welcome/funeral.html.erb
<%= render :partial => "slider", :locals => {:btitle => @btitle, :stitle => @stitle, :search_text => @search_text} %>

<div id="theword" class="row fill-all-form">
  <div class="col-md-8 col-md-offset-2 col-xs-12 form-page tag-box-v2 byenote-form-page">
    <%= form_for(@byenote) do |f| %>
      <%= render :partial => "funeral_form", :locals => {:f => f} %>
    <% end %>
  </div>
</div>
<%= render :partial => "contactus", :locals => { } %>

app/views/welcome/index.html.erb
<div class="wrapper">
  <%= render :partial => "slider", :locals => {:btitle => @btitle, :stitle => @stitle, :search_text => @search_text} %>

  <div class="container content-sm">
      <div class="text-center margin-bottom-50">
          <h2 class="title-v2 title-center">再見手札的特色</h2>
      </div>

      <div class="row content-boxes-v4">
          <div class="col-md-4 md-margin-bottom-40">
              <i class="pull-left fa fa-lightbulb-o"></i>
              <div class="content-boxes-in-v4">
                  <h2>完整溝通</h2>
                  <p>器捐意願、安寧意願、醫療訣擇、喪葬意願，再見手札讓您完整且方便的與家人溝通意願</p>
              </div>
          </div>
          <div class="col-md-4 md-margin-bottom-40">
              <i class="pull-left fa fa-flash"></i>
              <div class="content-boxes-in-v4">
                  <h2>快速分享</h2>
                  <p>再見手札可以快速分享您的意願給家人，輕鬆溝通這些嚴肅的議題，也希望您能分享給親朋好友，邀請大家一起加入器官捐贈的行列!</p>
              </div>
          </div>
          <div class="col-md-4">
              <i class="pull-left fa fa-compress"></i>
              <div class="content-boxes-in-v4">
                  <h2>方便查詢</h2>
                  <p>不同於健保卡註記，再見手札讓家人隨⼿就能查詢您的意願</p>
              </div>
          </div>
      </div>
  </div>

  <div class="container content-md">
    <table class="table table-hover">
      <thead>
        <tr><th colspan=3 class="text-center success"><h2>健保卡註記器捐、安寧意願 vs 再見手札</h2></th></tr>
        <tr>
          <th colspan=1 class="text-center"></th>
          <th colspan=1 class="text-center col-xs-5"><h4>健保卡註記意願</h4></th>
          <th colspan=1 class="text-center col-xs-5"><h4>再見手札</h4></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><h4>表達方式</h4></td>
          <td>
            紙本作業<br>
            1. 下載列印<a href="file:///Users/sky/Downloads/1021029_SignCard-DM%20(1).pdf">器官捐贈同意書</a><br>
            下載列印<a href="http://www.hospice.org.tw/2009/chinese/relax/relax-20130524-1.pdf">預立安寧緩和醫療暨維生醫療抉擇意願書</a><br>
            2. 填寫完畢後找見證人簽名<br>
            3. 分別寄回 器官捐贈移植登錄中心、台灣安寧照顧協會<br>
            4. 約 30 ~ 45 天，健保卡註記完成<br>
          </td>
          <td>
            <h4><u>快速</u></h4>
            點選、註冊、一分鐘完成
          </td>
        </tr>
        <tr>
          <td><h4>查詢方式</h4></td>
          <td>
            1. 到醫院查詢: 持個人或親友的健保卡至醫院讀卡機查詢意願<br>
            2. 線上查詢: 或到<a href="https://hpcod.mohw.gov.tw/HospWeb/MOPages/login.aspx">衛福部</a>網站使用健保卡、自然人憑證(需要讀卡機)查詢
          </td>
          <td>
            <h4><u>方便</u></h4>
            使用手機、電腦到 <%= link_to '再見手札查詢頁面', search_path %> <br>
            輸入Email 查詢個人或親友的意願
          </td>
        </tr>
        <tr>
          <td><h4>修改方式</h4></td>
          <td>
            修改: 重新寄出器捐同意書、安寧意願書，約 30~45天，健保卡註記更新完成<br>
            撤回: 下載列印<a href="http://www.torsc.org.tw/advocacy/advocacy_04c.jsp#">器官捐贈意願撤回聲明書</a>，填寫後寄出<br>
          </td>
          <td>
            <h4><u>簡單</u></h4>
            使用手機、電腦 <%= link_to '登入再見手札', new_user_session_path %> <br>
            修改後儲存，立即更新完成
          </td>
        </tr>
        <tr>
          <td><h4>法律效力 與 現實</h4></td>
          <td>有法律效力，但醫師以家屬意願為主<br>
            即使是預立遺囑或已於健保卡註記，一旦有家屬不同意捐贈，醫院將以家屬意願為主
          </td>
          <td>
            <h4><u>效果相同</u></h4>
            無法律效力，但醫師以家屬意願為主<br>
            <u>因此請將您的再見手札分享給家屬</u><br>
          </td>
        </tr>
        <tr><td colspan=3 class="text-center"><a href="#theword" class="btn btn-default"><h3>開始填寫「再見手札」</h3></a></td></tr>
      </tbody>
    </table>
  </div>

<div class="founder-talk">
    <div class="parallax-quote-in">
        <p>
          再見手札 與 健保卡註記，實際效益是相同的
          <strong>因為最終決定權在家屬手上</strong><br>
          <span class="color-green">因此務必將你的意願分享給家屬、親友知悉</span><br>
          再見手札為了讓您方便建立、分享、查詢意願而生
        </p>
        <small>- 再見手札創辦人 Sky -</small>
    </div>
</div>

  <div class="">
    <div class="container content-md">
        <div class="row">
            <div class="col-md-6">
                <h2 class="title-v2">什麼是器官捐贈?</h2>
                <p>器官捐贈是當一個人的⽣命結束時，將可用的器官捐贈出來，移植給有需要的病⼈以延續他人生命，或使其獲得更好的⽣活品質。</p>
                <p>在台灣，捐贈者家屬若需要器官移植時將有優先權，因此器捐可以照顧您的家⼈</p><br>
            </div>
            <div class="col-md-6 content-boxes-v3">
                <div class="margin-bottom-30">
                    <i class="icon-custom icon-md rounded-x icon-bg-u fa fa-lightbulb-o"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm">使家人有器官移植優先權</h2>
                        <p>捐贈者三親等內家屬等候器官移植時將有優先權</p>
                    </div>
                </div>
                <div class="margin-bottom-30">
                    <i class="icon-custom icon-md rounded-x icon-bg-u fa fa-lightbulb-o"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm">翻轉20個人的命運</h2>
                        <p>如果您捐出5個器官，可以幫助5個家庭 ，大約可以改變20個人的人生</p>
                    </div>
                </div>
                <div class="margin-bottom-30">
                    <i class="icon-custom icon-md rounded-x icon-bg-u fa fa-lightbulb-o"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm">減少家⼈的經濟負擔</h2>
                        <p>捐贈者家屬最高可獲得超過35萬元的喪葬和醫療費⽤補助</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <legend></legend>
  <div class="container content-md bg-grey">
      <div class="row">
          <div class="col-md-6">
              <h2 class="title-v2">什麼是安寧療護?</h2>
              <p>安寧療護，是指經醫師判定，罹患無法治癒之疾病，且病程近期內進展至死亡已不可避免之末期病人，臨終時得選擇不接受心肺復甦術(CPR)、不施行維生醫療、接受安寧緩和醫療。</p>
              <p>在台灣，超過三成民眾在臨終前被送到醫院接受按壓、急救、插管等「死亡套餐」酷刑，他們無謂的延長死亡過程。</p><br>
          </div>
          <div class="col-md-6 content-boxes-v3">
              <div class="margin-bottom-30">
                  <i class="icon-custom icon-md rounded-x icon-bg-u fa fa-lightbulb-o"></i>
                  <div class="content-boxes-in-v3">
                      <h2 class="heading-sm">讓生命末期不受醫療折磨</h2>
                      <p>臨終前使用加護病房的人中，有52.9%的人遭遇無效醫療的折磨無法善終</p>
                  </div>
              </div>
              <div class="margin-bottom-30">
                  <i class="icon-custom icon-md rounded-x icon-bg-u fa fa-lightbulb-o"></i>
                  <div class="content-boxes-in-v3">
                      <h2 class="heading-sm">減少家屬的愧疚與自責</h2>
                      <p>要家人為自己下一個生與死的決定是困難的，易使家屬感到愧疚和自責，並引起家屬間的紛爭</p>
                  </div>
              </div>
              <div class="margin-bottom-30">
                  <i class="icon-custom icon-md rounded-x icon-bg-u fa fa-lightbulb-o"></i>
                  <div class="content-boxes-in-v3">
                      <h2 class="heading-sm">讓家人享有充足的醫療資源</h2>
                      <p>無效醫療病人的費用佔所有加護病房的80%，每年無效醫療付出1,700億</p>
                  </div>
              </div>
          </div>

      </div>
  </div>
  <legend></legend>

  <div id="theword" class="form-top-space"></div>
  <div class="row fill-all-form">
    <div class="col-md-8 col-md-offset-2 col-xs-12 byenote-title">
      <h2 class="">再見手札</h2>
    </div>
    <div class="col-md-8 col-md-offset-2 col-xs-12 form-page tag-box-v2 byenote-form-page">

      <%= form_for(@byenote) do |f| %>
        <%= render :partial => "organ_form", :locals => {:f => f} %>
        <%= render :partial => "hospice_form", :locals => {:f => f} %>
        <%= render :partial => "funeral_form", :locals => {:f => f} %>

        <div class="row">
          <div class="heading"><h3 style="text-align:center;"><legend>給親友的話</legend></h3></div>
          <%= f.text_area :some_message, rows: 4, :class => "message_textarea", :placeholder => "告訴親友你寫下器官捐贈、安寧及喪葬意願的原因 (注意: 此項目開放不特定人查詢及閱覽，請避免個人隱私資訊)" %>
          <p>注意: 此項目開放不特定人查詢及閱覽，請避免個人隱私資訊</p>
        <div class="margin-bottom-20"></div>
          <p>*為便於查詢，以上資料皆開放任何人查詢及閱覽，請避免個人隱私資訊</p>
          <%= f.submit "儲存我的再見手札",:style => "width:100%;padding:10px;", :class => "btn btn-u" %>
        </div>
      <% end %>
    </div>
  </div>

<div class="founder-talk">
    <div class="parallax-quote-in">
        <p>如果我們出了意外，因為再見手札能讓自己、家人、他人更舒服些<br><span class="color-green">那就是我想做的事</span></p>
        <small>- 再見手札創辦人 Sky -</small>
    </div>
</div>

  <%= render :partial => "contactus", :locals => { } %>
</div>

app/views/welcome/read.html.erb
<p class="alert alert-success text-center">
   <%= flash[:success] %>
   <a href="" class="close" data-dismiss="alert">&#215;</a>
</p>
<div id="theword" class="row fill-all-form">
  <div class="col-md-8 col-md-offset-2 col-xs-12 form-page tag-box-v2 byenote-form-page">
    <%= form_for(@byenote) do |f| %>
      <%= render :partial => "welcome/organ_form", :locals => {:f => f } %>
      <%= render :partial => "welcome/hospice_form", :locals => {:f => f } %>
      <%= render :partial => "welcome/funeral_form", :locals => {:f => f } %>
      <div class="row">
          <div class="heading"><h3 style="text-align:center;"><legend>給親友的話</legend></h3></div>
          <%= f.text_area :some_message, rows: 4, :class => "message_textarea", :placeholder => "與親朋好友們道謝、道歉、道愛、道別" %>
      </div>
      <div class="margin-bottom-20"></div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        lockAllBox();
    });
</script>